owner: aigratusjohn-dotcom
repo: torrentio-status

sites:
  - name: Torrentio Manifest
    url: https://torrentio.strem.fun/manifest.json
    
notifications:
  - type: telegram
    botToken: $TELEGRAM_BOT_TOKEN
    chatId: $TELEGRAM_CHAT_ID

status-website:
  name: Torrentio Status

workflowSchedule:
  graphs: "0 0 * * *"
  static-site: "0 1 * * *"
  summary: "0 0 * * *"
  uptime: "*/5 * * * *"

assignees:
  - aigratusjohn-dotcom
