# Change this to your GitHub username: 
owner: aigratusjohn-dotcom
# Change this to your repository name:
repo: torrentio-status

# Add the websites you want to monitor here
sites:
  - name: Torrentio Manifest
    url: https://torrentio.strem.fun/manifest.json

# Configure your notification integrations here
notifications:
  # Docs: https://upptime.js.org/docs/notifications
  - type: telegram
    # Note: secrets are accessed with a "$" prefix
    # You've already set these in your repository's secrets
    botToken: $TELEGRAM_BOT_TOKEN
    chatId: $TELEGRAM_CHAT_ID

# Here you can customize your status page
status-website:
  # Add your custom domain below, or remove the next line if you don't have one
  # cname: demo.upptime.js.org
  # Or specify a custom URL for the navigation bar
  # link to your website
  name: Torrentio Status

# By default, Upptime checks every 5 minutes
workflowSchedule:
  graphs: "0 0 * * *"
  static-site: "0 1 * * *"
  summary: "0 0 * * *"
  uptime: "*/5 * * * *"

# Upptime also supports assigning issues to users
assignees:
  - aigratusjohn-dotcom
